FROM debian:latest

RUN apt update && apt install git cmake build-essential -y

COPY . /app
WORKDIR /app

RUN mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SERVER=OFF -DBUILD_CLIENT=ON && make

CMD ["./build/echolink_client"]